// tailwind.config.js
const colors = require('tailwindcss/colors')

module.exports = {
  purge: [],
  theme: {
    fontSize: {
      xs: '.75rem',
      sm: '.875rem',
      tiny: '.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      bigxl: '3.5rem',
      bigxlextra: '3.75rem',
      big: '4rem',
      morebig: '4.5rem',
      evenmorebig: '5rem',
      biggest: '5.5rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '6rem',
      '7xl': '7rem',
      '8xl': '8rem',
      '12xl': '12rem',
      '16xl': '16rem',
      '18xl': '18rem',
      '20xl': '20rem',
      '32xl': '32rem',
      '64xl': '64rem',
    },
    rotate: {
      '-28': '-28deg',
    },
    extend: {
      spacing: {
        120: '740px',
      },
      colors: {
        orange: colors.orange,
        teal: colors.teal,
        'glow-primary': '#ff2020',
        'glow-secondary': '#ec008c',
        secondary: 'var(--secondary)',
        'primary-light': 'var(--primary-light)',
        'secondary-light': 'var(--secondary-light)',
        'background-primary': 'var(--background-primary)',
        'background-secondary': 'var(--background-secondary)',
        'text-light': 'var(--text-light)',
        'text-lighter': 'var(--text-lighter)',
        'text-dark': 'var(--text-dark)',
        'text-darker': 'var(--text-darker)',
        primary: {
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
        },
        button: {
          DEFAULT: 'var(--text-button)',
          disabled: 'var(--text-button-disabled)',
        },
        field: {
          DEFAULT: 'var(--border-input)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          hover: 'var(--color-accent-hover)',
          'hover-outline': 'var(--color-accent-hover-outline)',
          disabled: 'var(--color-accent-disabled)',
        },
      },
    },
  },
  variants: {},
  plugins: [],
}
